* XML简介
** 什么是XML？
- XML指可扩展标记语言
- XML是一种标记语言，很类似HTML
- XML的设计宗旨是传输数据，而非现实数据
- XML的标签没有被预定义。你需要自行定义标签
- XML被设计为具有自我描述性。
- XML是W3C的推荐标准

** XML语法
- 所有XML元素必须有关闭标签
- XML标签对大小写敏感
- XML必须要正确嵌套
- XMl文档必须要有根元素
- XML的属性值需要加引号
- 实体引用
在XML中有5个预定义的实体引用：
| &lt   | < | 小于   |
| &gt   | > | 大于   |
| &amp  | & | 与号   |
| &apos | ' | 单引号 |
| &quot | " | 引号   |
|       |   |        |
注释：在 XML 中，只有字符 "<" 和 "&" 确实是非法的。大于号是合法的，但是用实体引用来代替它是一个好习惯。"
- XML中的注释
在XML中编写注释的语法与HTML的语法很相似：
<!-- This is a comment -->
- 在XML中，空格会被保留

- XML以LF存储换行
** XML元素
http://www.w3school.com.cn/xml/xml_elements.asp

- XML命名规则
XML 匀速必须遵守以下命名规则：
 a) 名称可以含字幕、数字以及其他的字符串
b) 名称不能以数字或者标点符号开始
c) 名称不能以字符“xml”（或者XML、xml）开始
d）名称不能包含空格

可使用任何名称，没有保留的字词。
- 最佳的命名习惯
使名称具有描述性。使用下划线的名称也很不错。
名称应当比较简短，比如：<book_title>，而不是：<the_title_of_the_book>。
避免 "-" 字符。如果您按照这样的方式进行命名："first-name"，一些软件会认为你需要提取第一个单词。
避免 "." 字符。如果您按照这样的方式进行命名："first.name"，一些软件会认为 "name" 是对象 "first" 的属性。
避免 ":" 字符。冒号会被转换为命名空间来使用（稍后介绍）。
XML 文档经常有一个对应的数据库，其中的字段会对应 XML 文档中的元素。有一个实用的经验，即使用数据库的名称规则来命名 XML 文档中的元素。
非英语的字母比如 éòá 也是合法的 XML 元素名，不过需要留意当软件开发商不支持这些字符时可能出现的问题。

- XML元素是可扩展的
**  XML属性
注释：如果属性值本身包含双引号，那么有必要使用单引号包围它，就像这个例子：
<gangster name='George "Shotgun" Ziegler'>
- 我最喜欢的方式
<note>
<date>
  <day>08</day>
  <month>08</month>
  <year>2008</year>
</date>
<to>George</to>
<from>John</from>
<heading>Reminder</heading>
<body>Don't forget the meeting!</body>
</note>
