# Site wide configuration

title: "worldwar2008's Tech Blog"
description: "Collection of what I think and overcome"
logo: log-1.jpg # 120x120 px default image used for Twitter summary card
teaser: teaser.jpg # 400x250 px default teaser image used in image archive grid
locale: 
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: worldwar2008(郭强)
  email: worldwar2008@126.com
  twitter: worldwar2008
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: worldwar2008


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
